### ISSUE TITLE
some question about selective search

### ISSUE THREAD

**Issue by AndyYuan96** [hologerry/SoCo#4]
hi，hologerry， thanks for open source the code, I just wonder does use a detector trained on object detection dataset to generate proposal can get a better result than selective search, as detector is better than selective search, I just wonder how important the proposal generation method's performance to SoCo framework, detector vs selective search.

**Comment by hologerry** [comment]
Hi @AndyYuan96 , thanks for your interests, good question!
To verify the importance of the proposal generation, we perform the experiments of Table 5(c), as we can see good proposals can help the model learn better representations for downstream object detection.
Since we focus on aligning the pertaining and finetuning, it definitely would be better for using detectors' object proposals. But it is out of the scope of self-supervised learning, we have not performed experiments on this.
